name: checkout-action
description: GitHub Action for checking out a repository. (Simplified actions/checkout alternative that does not depend on Node.js.)

inputs:
  token:
    description: GitHub token for checking out a repository.
    required: false

# Note:
# - inputs.* should be manually mapped to INPUT_* due to https://github.com/actions/runner/issues/665
# - For context containing path, use GITHUB_*/RUNNER_* instead of github.*/runner.* due to https://github.com/actions/runner/issues/2185
runs:
  using: composite
  steps:
    - run: |
        bail() {
          printf '::error::checkout-action: %s\n' "$*"
          exit 1
        }
        warn() {
          printf '::warning::checkout-action: %s\n' "$*"
        }
        if command -v /bin/grep >/dev/null; then
          grep=/bin/grep
        elif command -v /usr/bin/grep >/dev/null; then
          grep=/usr/bin/grep
        else
          grep=$(command -v grep)
          if [ -n "${HAS_TOKEN}" ]; then
            bail "grep is unavailable at standard location; found ${grep}"
          else
            warn "grep is unavailable at standard location; using ${grep}"
          fi
        fi
        # If /bin/sh is dash, environment variable containing % is not imported, but is fine
        # because it also means that it will not be exposed to subprocess.
        if /usr/bin/env | "${grep}" -Eq '^BASH_FUNC_'; then
          bail 'bash function injection via BASH_FUNC_ environment variable is not allowed for security reasons'
        fi
        if ! command -v bash >/dev/null; then
          if command -v /bin/sleep >/dev/null; then
            sleep=/bin/sleep
          elif command -v /usr/bin/sleep >/dev/null; then
            sleep=/usr/bin/sleep
          else
            sleep=$(command -v sleep)
            if [ -n "${HAS_TOKEN}" ]; then
              bail "sleep is unavailable at standard location; found ${sleep}"
            else
              warn "sleep is unavailable at standard location; using ${sleep}"
            fi
          fi
          retry() {
            for i in 1 2 3 4 5 6 7 8 9 10; do
              if "$@"; then
                return 0
              else
                "${sleep}" "${i}"
              fi
            done
            "$@"
          }
          if "${grep}" -Eq '^ID="?alpine"?$|^ID_LIKE=.*alpine' /etc/os-release; then
            printf '::group::Install packages required for checkout-action (bash)\n'
            # NB: sync with main.sh
            if command -v /usr/bin/sudo >/dev/null; then
              retry /usr/bin/sudo /sbin/apk --no-cache add bash
            elif command -v /usr/bin/doas >/dev/null; then
              retry /usr/bin/doas /sbin/apk --no-cache add bash
            else
              retry /sbin/apk --no-cache add bash
            fi
            printf '::endgroup::\n'
          elif "${grep}" -Eq '^ID="?openwrt"?$|^ID_LIKE=.*openwrt' /etc/os-release; then
            printf '::group::Install packages required for checkout-action (bash)\n'
            # NB: sync with main.sh
            # https://forum.openwrt.org/t/the-future-is-now-opkg-vs-apk/201164
            if command -v /usr/bin/apk >/dev/null; then
              if command -v /usr/bin/sudo >/dev/null; then
                retry /usr/bin/sudo /usr/bin/apk --no-cache add bash
              else
                retry /usr/bin/apk --no-cache add bash
              fi
            else
              if command -v /usr/bin/sudo >/dev/null; then
                /usr/bin/sudo /bin/mkdir -p -- /var/lock
                retry /usr/bin/sudo /bin/opkg update
                retry /usr/bin/sudo /bin/opkg install bash
              else
                /bin/mkdir -p -- /var/lock
                retry /bin/opkg update
                retry /bin/opkg install bash
              fi
            fi
            printf '::endgroup::\n'
          else
            bail 'this action requires bash'
          fi
        fi
        if command -v /bin/bash >/dev/null; then
          /bin/bash --noprofile --norc "${GITHUB_ACTION_PATH:?}/main.sh"
        else
          bash=$(command -v bash)
          if [ -n "${HAS_TOKEN}" ]; then
            bail "bash is unavailable at standard location; found ${bash}"
          else
            warn "bash is unavailable at standard location; using ${bash}"
            "${bash}" --noprofile --norc "${GITHUB_ACTION_PATH:?}/main.sh"
          fi
        fi
      shell: /usr/bin/env -u ENV -u BASH_ENV -u CDPATH -u SHELLOPTS -u BASHOPTS /bin/sh -eu {0} # zizmor: ignore[misfeature] false positive
      env:
        # NB: Sync with Windows case.
        INPUT_TOKEN: ${{ inputs.token }}
        # TODO: support in input options
        INPUT_REPOSITORY: ${{ github.repository }}
        INPUT_SERVER_URL: ${{ github.server_url }}
        INPUT_SHA: ${{ github.sha }}
        INPUT_REF: ${{ github.ref }}
        HAS_TOKEN: ${{ inputs.token == '' && '' || '1' }}
        RUNNER_OS: ${{ runner.os }}
      if: runner.os != 'Windows'
    # Use pwsh and retry on bash startup failure to work around windows-11-arm runner bug:
    # https://github.com/actions/partner-runner-images/issues/169
    - run: |
        Set-StrictMode -Version Latest
        if (Test-Path "Env:ENV") { Remove-Item Env:\ENV }
        if (Test-Path "Env:BASH_ENV") { Remove-Item Env:\BASH_ENV }
        if (Test-Path "Env:CDPATH") { Remove-Item Env:\CDPATH }
        if (Test-Path "Env:SHELLOPTS") { Remove-Item Env:\SHELLOPTS }
        if (Test-Path "Env:BASHOPTS") { Remove-Item Env:\BASHOPTS }
        if (Test-Path "Env:BASH_FUNC_*") {
          Write-Output "::error::checkout-action: bash function injection via BASH_FUNC_ environment variable is not allowed for security reasons"
          exit 1
        }
        $bash = (Get-Command bash).Path
        switch ($bash) {
          "C:\Program Files\Git\bin\bash.exe" {} # default
          "C:\msys64\usr\bin\bash.exe" {} # msys64
          "C:\tools\cygwin\bin\bash.exe" {} # cygwin
          default {
            if ("$env:HAS_TOKEN" -ne "") {
              Write-Output "::error::checkout-action: bash is unavailable at standard location; found $bash"
              exit 1
            } else {
              Write-Output "::warning::checkout-action: bash is unavailable at standard location; using $bash"
            }
          }
        }
        for ($i=1; $i -le 10; $i++) {
          $prev_err_action = $ErrorActionPreference
          $ErrorActionPreference = "Continue"
          & bash --noprofile --norc "$env:GITHUB_ACTION_PATH\main.sh"
          $code = $LASTEXITCODE
          $ErrorActionPreference = "$prev_err_action"
          if (Test-Path "$env:USERPROFILE\.checkout-action-init") {
            # If bash started successfully, main.sh creates init file.
            Remove-Item "$env:USERPROFILE\.checkout-action-init" -Force
            exit $code
          }
          if ($i -lt 10) {
            Write-Output "::warning::checkout-action: checkout failed due to bash startup failure (<https://github.com/actions/partner-runner-images/issues/169>); retrying..."
          }
        }
        Write-Output "::error::checkout-action: checkout failed due to bash startup failure (<https://github.com/actions/partner-runner-images/issues/169>); this maybe resolved by re-running job"
        exit 1
      shell: pwsh
      env:
        # NB: Sync with non-Windows case.
        INPUT_TOKEN: ${{ inputs.token }}
        # TODO: support in input options
        INPUT_REPOSITORY: ${{ github.repository }}
        INPUT_SERVER_URL: ${{ github.server_url }}
        INPUT_SHA: ${{ github.sha }}
        INPUT_REF: ${{ github.ref }}
        HAS_TOKEN: ${{ inputs.token == '' && '' || '1' }}
        RUNNER_OS: ${{ runner.os }}
      if: runner.os == 'Windows'
