name: checkout-action
description: GitHub Action for checking out a repository. (Simplified actions/checkout alternative that does not depend on Node.js.)

# Note:
# - inputs.* should be manually mapped to INPUT_* due to https://github.com/actions/runner/issues/665
# - Use GITHUB_*/RUNNER_* instead of github.*/runner.* due to https://github.com/actions/runner/issues/2185
runs:
  using: composite
  steps:
    - name: Prepare
      id: prepare
      run: |
        set -eu
        if ! command -v bash >/dev/null; then
          if command -v busybox >/dev/null; then
            if test -n "${GITHUB_OUTPUT:-}"; then
              printf 'shell=busybox sh -e {0}\n' >>"${GITHUB_OUTPUT}"
              exit
            fi
          fi
          printf '::error::checkout-action requires bash or busybox\n'
          exit 1
        fi
      shell: sh
      if: runner.os == 'Linux'
    - name: Checkout
      run: |
        case "${CURRENT_SHELL}" in
          busybox*) busybox sh "${GITHUB_ACTION_PATH:?}/main.sh" ;;
          *) bash --noprofile --norc "${GITHUB_ACTION_PATH:?}/main.sh" ;;
        esac
      shell: ${{ steps.prepare.outputs.shell || 'bash' }}
      env:
        CURRENT_SHELL: ${{ steps.prepare.outputs.shell }}
