name: CI

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash --noprofile --norc -CeEuxo pipefail {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  tidy:
    uses: taiki-e/github-actions/.github/workflows/tidy.yml@3c1cac16ef654d1febb66f21f328fa167f0d2fef # main
    permissions:
      contents: write # for creating branch for pr
      pull-requests: write # unused (used in `codegen-automerge: true` case)
      security-events: write # for github/codeql-action/*
    secrets:
      PR_TOKEN_APP_PRIVATE_KEY: ${{ secrets.PR_TOKEN_APP_PRIVATE_KEY }}

  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Test all non-deprecated images listed in https://github.com/actions/runner-images#available-images
          # and https://github.com/actions/partner-runner-images#available-images,
          # and also msys64 & cygwin, which have different behavior than default https://github.com/taiki-e/install-action/pull/518#issuecomment-2160736760.
          # (msys64/cygwin is not installed on arm runner https://github.com/actions/partner-runner-images/issues/88)
          - os: ubuntu-22.04
          - os: ubuntu-22.04-arm
          - os: ubuntu-24.04
          - os: ubuntu-24.04-arm
          - os: ubuntu-slim
          - os: macos-14
          - os: macos-15
          - os: macos-15-intel
          - os: macos-26
          - os: windows-2022
          - os: windows-2022
            bash: msys64
          - os: windows-2022
            bash: cygwin
          - os: windows-2025
          - os: windows-2025
            bash: msys64
          - os: windows-2025
            bash: cygwin
          - os: windows-11-arm
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - run: |
          printf '%s\n' 'C:\msys64\mingw32\bin' >>"${GITHUB_PATH}"
          printf '%s\n' 'C:\msys64\usr\bin' >>"${GITHUB_PATH}"
        if: matrix.bash == 'msys64'
      - run: |
          choco install --no-progress --requirechecksums cygwin
          printf '%s\n' 'C:\tools\cygwin\bin' >>"${GITHUB_PATH}"
          printf '%s\n' 'C:\tools\cygwin\usr\bin' >>"${GITHUB_PATH}"
        if: matrix.bash == 'cygwin'
      # TODO: use the current branch instead of @main
      - uses: taiki-e/checkout-action@main # zizmor: ignore[unpinned-uses] # For test.
      - run: git ls-files
      - run: test -f ./tools/tidy.sh
      - run: ./tools/tidy.sh
        if: startsWith(matrix.os, 'ubuntu') && matrix.os != 'ubuntu-slim'
  # For comparison
  # actions-checkout:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os:
  #         - ubuntu-latest
  #         - macos-latest
  #         - windows-latest
  #   runs-on: ${{ matrix.os }}
  #   timeout-minutes: 60
  #   steps:
  #     - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
  #       with:
  #         persist-credentials: false
  #     - run: git ls-files
  #     - run: test -f ./tools/tidy.sh
  #     - run: ./tools/tidy.sh
  #       if: startsWith(matrix.os, 'ubuntu')

  test-container:
    strategy:
      fail-fast: false
      matrix:
        container:
          - ubuntu:14.04 # glibc 2.19, git 1.9, EoL, end of ESM
          - ubuntu:16.04 # glibc 2.23, git 2.7, EoL, end of ESM
          - ubuntu:18.04 # glibc 2.27, git 2.17, EoL
          - ubuntu:20.04 # glibc 2.31, git 2.25, EoL
          - ubuntu:22.04 # glibc 2.35, git 2.34
          - ubuntu:24.04 # glibc 2.39, git 2.43
          - ubuntu:26.04 # glibc 2.42, git 2.53
          - ubuntu:rolling # glibc
          - debian:9-slim # glibc 2.24, git 2.11, EoL, end of LTS
          - debian:10-slim # glibc 2.28, git 2.20, EoL, end of LTS
          - debian:11-slim # glibc 2.31, git 2.30, EoL
          - debian:12-slim # glibc 2.36, git 2.39
          - debian:13-slim # glibc 2.41, git 2.47
          - debian:testing # glibc
          - fedora:latest # glibc
          - almalinux:8 # glibc 2.28, git 2.43
          - almalinux:8-minimal # glibc 2.28, git 2.43
          - almalinux:9 # glibc 2.34, git 2.47
          - almalinux:9-minimal # glibc 2.34, git 2.47
          - almalinux:10 # glibc 2.39, git 2.47
          - almalinux:10-minimal # glibc 2.39, git 2.47
          - centos:6 # glibc 2.12, git 1.7, EoL
          - centos:7 # glibc 2.17, git 1.8, EoL
          - opensuse/leap:15.0 # glibc 2.26, git 2.16, EoL
          # Skip intermediate versions that have reached EoL by default.
          # - opensuse/leap:15.1 # glibc 2.26, git 2.26, EoL
          # - opensuse/leap:15.2 # glibc 2.26, git 2.26, EoL
          # - opensuse/leap:15.3 # glibc 2.31, git 2.35, EoL
          # - opensuse/leap:15.4 # glibc 2.31, git 2.35, EoL
          # - opensuse/leap:15.5 # glibc 2.31, git 2.35, EoL
          - opensuse/leap:15.6 # glibc 2.38, git 2.51
          - opensuse/leap:16.0 # glibc 2.40, git 2.51
          - opensuse/tumbleweed:latest # glibc
          - archlinux:latest # glibc
          - alpine:3.2 # musl 1.1.11, git 2.4, EoL
          # Skip intermediate versions that have reached EoL by default.
          # - alpine:3.3 # musl 1.1.12, git 2.8, EoL
          # - alpine:3.4 # musl 1.1.14, git 2.8, EoL
          # - alpine:3.5 # musl 1.1.15, git 2.11, EoL
          # - alpine:3.6 # musl 1.1.16, git 2.13, EoL, broken env command
          # - alpine:3.7 # musl 1.1.18, git 2.15, EoL, broken env command
          # - alpine:3.8 # musl 1.1.19, git 2.18, EoL
          # - alpine:3.9 # musl 1.1.20, git 2.20, EoL
          # - alpine:3.10 # musl 1.1.22, git 2.22, EoL
          # - alpine:3.11 # musl 1.1.24, git 2.24, EoL
          # - alpine:3.12 # musl 1.1.24, git 2.26, EoL
          # - alpine:3.13 # musl 1.2.2, git 2.30, EoL
          # - alpine:3.14 # musl 1.2.2, git 2.32, EoL
          # - alpine:3.15 # musl 1.2.2, git 2.34, EoL
          # - alpine:3.16 # musl 1.2.3, git 2.36, EoL
          # - alpine:3.17 # musl 1.2.3, git 2.39, EoL
          # - alpine:3.18 # musl 1.2.4, git 2.40, EoL
          # - alpine:3.19 # musl 1.2.4, git 2.43, EoL
          # - alpine:3.20 # musl 1.2.5, git 2.45, EoL
          - alpine:3.21 # musl 1.2.5, git 2.47
          - alpine:3.22 # musl 1.2.5, git 2.49
          - alpine:3.23 # musl 1.2.5, git 2.52
          - openwrt/rootfs:x86_64-23.05.6 # musl 1.2.4, git 2.43, opkg, EoL
          - openwrt/rootfs:x86_64-24.10.6 # musl 1.2.5, git 2.50, opkg
          - openwrt/rootfs:x86_64 # musl, apk
    runs-on: ubuntu-latest
    timeout-minutes: 60
    container: ${{ matrix.container }}
    steps:
      - name: Install requirements (old debian)
        run: |
          # In Debian, the old repositories is removed from the main mirrors some time after end of LTS.
          codename=$(grep -E '^VERSION_CODENAME=' /etc/os-release | cut -d= -f2)
          sed -i /etc/apt/sources.list -e 's/deb.debian.org/archive.debian.org/g' \
            -e 's|security.debian.org|archive.debian.org/|g' \
            -e "/${codename}-updates/d"
        if: startsWith(matrix.container, 'debian:9') || startsWith(matrix.container, 'debian:10')
      - name: Install requirements (centos)
        run: |
          retry() {
            for i in {1..10}; do
              if "$@"; then
                return 0
              else
                sleep "${i}"
              fi
            done
            "$@"
          }
          # In CentOS, the old repositories is removed from the main mirrors just after EoL.
          # https://github.com/rust-lang/rust/pull/126352
          sed -i /etc/yum.repos.d/*.repo -e 's!^mirrorlist!#mirrorlist!' \
            -e 's!^#baseurl=http://mirror.centos.org/!baseurl=https://vault.centos.org/!'
          sed -i 's/enabled=1/enabled=0/' /etc/yum/pluginconf.d/fastestmirror.conf
          if [[ "${CONTAINER}" == "centos:6" ]]; then
            # CentOS 6's git (1.7.1) has no --local/--no-recurse-submodules.
            # And even if we don't pass those flags, that version of git will not work
            # anyway due to of "fatal: Couldn't find remote ref" error.
            retry yum install -y openssh-clients perl perl-Error perl-TermReadKey rsync
            retry rpm -i \
              https://vault.ius.io/el6/x86_64/packages/p/perl-Git18-1.8.5.5-4.ius.el6.noarch.rpm \
              https://vault.ius.io/el6/x86_64/packages/g/git18-1.8.5.5-4.ius.el6.x86_64.rpm
          fi
        env:
          CONTAINER: ${{ matrix.container }}
        if: startsWith(matrix.container, 'centos')
      # For test
      # - run: /usr/bin/apt-get -o Acquire::Retries=10 -qq update && /usr/bin/apt-get -o Acquire::Retries=10 -o Dpkg::Use-Pty=0 install -y --no-install-recommends sudo
      #   if: startsWith(matrix.container, 'debian') || startsWith(matrix.container, 'ubuntu')
      # - run: /usr/bin/dnf install -y sudo
      #   if: startsWith(matrix.container, 'fedora') || (startsWith(matrix.container, 'almalinux') && !endsWith(matrix.container, '-minimal'))
      # - run: /usr/bin/microdnf install -y sudo
      #   if: startsWith(matrix.container, 'almalinux') && endsWith(matrix.container, '-minimal')
      # - run: /usr/bin/yum install -y sudo
      #   if: startsWith(matrix.container, 'centos')
      # - run: /usr/bin/zypper install -y sudo
      #   if: startsWith(matrix.container, 'opensuse')
      # - run: /usr/bin/pacman -Sy --noconfirm sudo
      #   if: startsWith(matrix.container, 'archlinux')
      # - run: /sbin/apk --no-cache add sudo
      #   shell: sh
      #   if: startsWith(matrix.container, 'alpine')
      # - run: /usr/bin/apk --no-cache add sudo
      #   shell: sh
      #   if: matrix.container == 'openwrt/rootfs:x86_64'
      # - run: |
      #     /bin/mkdir -p -- /var/lock
      #     /bin/opkg update
      #     /bin/opkg install sudo
      #   shell: sh
      #   if: startsWith(matrix.container, 'openwrt') && matrix.container != 'openwrt/rootfs:x86_64'
      # TODO: use the current branch instead of @main
      - uses: taiki-e/checkout-action@main # zizmor: ignore[unpinned-uses] # For test.
      - run: git ls-files
      - run: test -f ./tools/tidy.sh
